
# Define global constants to identify events
EVT_NEW_ROUND = 0
EVT_NEW_HAND = 1
EVT_UI_GET_CARD = 2
EVT_CARD_PLAYED = 3
EVT_UI_PLAYER_LEFT = 4
EVT_END_OF_TRICK = 5
EVT_NEW_DEAL = 6
CONSOLE = 7
EVT_NEW_BID = 8
EVT_COINCHE = 9
EVT_SURCOINCHE = 10
EVT_UI_COINCHE = 11
EVT_UI_SURCOINCHE = 12
EVT_UI_GET_BID = 13
EVT_DEAL_SCORE = 14
EVT_UPDATE_SCORE = 15
EVT_END_BIDDING = 16
CONSOLE_RED = 17
EVT_UI_COINCHE = 18
EVT_BELOTE = 19
EVT_REBELOTE = 20
EVT_INVALID_BELOTE = 21
